# Generated by Django 5.0 on 2024-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupen',
            fields=[
                ('coupen_id', models.BigAutoField(default=0, primary_key=True, serialize=False, unique=True)),
                ('coupen_name', models.CharField(blank=True, max_length=300, null=True)),
                ('coupen_code', models.CharField(unique=True)),
                ('coupen_price', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('expiration_date', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_expire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
