# Generated by Django 5.0 on 2024-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='coupen_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
