# Generated by Django 5.0 on 2024-05-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0002_alter_coupen_coupen_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupen',
            old_name='coupen_price',
            new_name='coupen_percentage',
        ),
    ]
