# Generated by Django 5.0 on 2024-05-03 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0003_rename_coupen_price_coupen_coupen_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='coupen_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupen',
            name='used_users',
            field=models.ManyToManyField(related_name='coupon_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
