# Generated by Django 5.0 on 2024-05-03 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0004_coupen_coupen_stock_coupen_used_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_coupon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('used_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='admin_coupen_app.coupen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
