# Generated by Django 5.0 on 2024-05-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0005_user_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupen',
            name='used_users',
        ),
    ]
