# Generated by Django 5.0 on 2024-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0007_coupen_used_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
