# Generated by Django 5.0 on 2024-03-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_active',
            field=models.BooleanField(default=True),
        ),
    ]
