# Generated by Django 5.0 on 2024-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0002_banner_banner_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
