# Generated by Django 5.0 on 2024-03-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_app', '0004_alter_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('first_banner', 'First Banner'), ('secondary_banner', 'Secondary Banner'), ('third_banner', 'Third Banner')], default='first_banner'),
        ),
    ]
