# Generated by Django 5.0 on 2024-04-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_product_app', '0042_wishlist'),
        ('cart_app', '0008_cart_cart_customer_owner_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=250)),
                ('payment_id', models.CharField(null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('out_of_delivery', 'Out of delivery'), ('delivered', 'Delivered')], default='processing')),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='admin_product_app.colors')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_constomer', to='cart_app.owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='admin_product_app.products')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_storage', to='admin_product_app.storage')),
            ],
        ),
    ]
