# Generated by Django 5.0 on 2024-05-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0002_remove_review_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
