# Generated by Django 5.0 on 2024-04-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
