# Generated by Django 5.0 on 2024-05-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='update_at',
        ),
    ]
