# Generated by Django 5.0 on 2024-04-30 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0042_wishlist'),
        ('checkout_app', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='review',
        ),
    ]
