# Generated by Django 5.0 on 2024-04-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0006_rename_rating_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
