# Generated by Django 5.0 on 2024-05-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0007_review_update_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
    ]
