# Generated by Django 5.0 on 2024-04-17 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_product_app', '0042_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('stage', models.IntegerField(choices=[(0, 'cart'), (1, 'order')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartcolor', to='admin_product_app.colors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitem', to='admin_product_app.products')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cartstorage', to='admin_product_app.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartorder', to='cart_app.owner')),
            ],
        ),
    ]
