# Generated by Django 5.0 on 2024-05-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
    ]
