# Generated by Django 5.0 on 2024-04-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0003_alter_owner_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_constomer', to='cart_app.owner'),
        ),
    ]
