# Generated by Django 5.0 on 2024-05-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_order_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
