# Generated by Django 5.0 on 2024-05-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Processing'), (2, 'Shipped'), (3, 'Out of delivery'), (4, 'Delivered'), (5, 'Cancel')], default=0),
        ),
    ]
