# Generated by Django 5.0 on 2024-05-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
