# Generated by Django 5.0 on 2024-04-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_owner_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_customer',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='customer',
        ),
    ]
