# Generated by Django 5.0 on 2024-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
