# Generated by Django 5.0 on 2024-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_cart_cart_customer_owner_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('processing', 'Processing'), ('out_of_delivery', 'Out of delivery'), ('delivered', 'Delivered')], default='cart'),
        ),
    ]
