# Generated by Django 5.0 on 2024-05-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_address'),
        ('admin_product_app', '0042_wishlist'),
        ('cart_app', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(0, 'Cart'), (1, 'Processing'), (2, 'Shipped'), (3, 'Out of delivery'), (4, 'Delivered'), (5, 'Cancel')], default=0)),
                ('total_price', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='admin_product_app.colors')),
                ('order_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_address', to='admin_app.address')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_costm', to='cart_app.owner')),
                ('order_payment', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_payment', to='cart_app.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='admin_product_app.products')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_storage', to='admin_product_app.storage')),
            ],
        ),
    ]
