# Generated by Django 5.0 on 2024-04-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_address_user'),
        ('admin_product_app', '0042_wishlist'),
        ('cart_app', '0009_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('payment_id', models.CharField(default=0, null=True)),
                ('payment_mode', models.CharField(default='COD', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('cart', 'Cart'), ('processing', 'Processing'), ('out_of_delivery', 'Out of delivery'), ('delivered', 'Delivered')], default='cart')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_color', to='admin_product_app.colors')),
                ('order_address', models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_address', to='admin_app.address')),
                ('order_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_costm', to='cart_app.owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='admin_product_app.products')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_storage', to='admin_product_app.storage')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
