# Generated by Django 5.0 on 2024-05-02 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
