# Generated by Django 5.0 on 2024-04-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_order_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='stage',
        ),
    ]
