# Generated by Django 5.0 on 2024-05-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
    ]
