# Generated by Django 5.0 on 2024-04-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_address_user'),
        ('cart_app', '0013_remove_owner_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordered_address', to='admin_app.address'),
        ),
    ]
