# Generated by Django 5.0 on 2024-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0014_order_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
