# Generated by Django 5.0 on 2024-05-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_owner_coupen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='coupen',
            new_name='coupon_percentage',
        ),
    ]
