# Generated by Django 5.0 on 2024-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Processing'), (2, 'Out of delivery'), (3, 'Delivered')], default=0),
        ),
    ]
