# Generated by Django 5.0 on 2024-05-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_coupen_app', '0007_coupen_used_users'),
        ('cart_app', '0017_rename_coupen_owner_coupon_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='coupon_percentage',
        ),
        migrations.AddField(
            model_name='owner',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_coupon', to='admin_coupen_app.coupen'),
        ),
    ]
