# Generated by Django 5.0 on 2024-04-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Processing'), (2, 'Shipped'), (3, 'Out of delivery'), (4, 'Delivered'), (5, 'Cancel')], default=0),
        ),
    ]
