# Generated by Django 5.0 on 2024-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0018_remove_owner_coupon_percentage_owner_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='coupon',
        ),
        migrations.AddField(
            model_name='owner',
            name='coupon_code',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='coupon_percentage',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
