# Generated by Django 5.0 on 2024-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0019_remove_owner_coupon_owner_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='coupon_percentage',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
