# Generated by Django 5.0 on 2024-05-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0020_alter_owner_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_payment',
        ),
    ]
