# Generated by Django 5.0 on 2024-05-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0021_order_coupon_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cart'), (1, 'Processing'), (2, 'Shipped'), (3, 'Out of delivery'), (4, 'Delivered'), (5, 'Cancel'), (6, 'Return'), (7, 'Refund')], default=0),
        ),
    ]
