# Generated by Django 5.0 on 2024-05-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0024_order_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_customer',
        ),
    ]
