# Generated by Django 5.0 on 2024-05-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0025_remove_order_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_costm', to='cart_app.owner'),
            preserve_default=False,
        ),
    ]
