# Generated by Django 5.0 on 2024-05-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0026_order_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
    ]
