# Generated by Django 5.0 on 2024-05-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0030_order_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('order_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_sale', to='cart_app.order')),
            ],
        ),
    ]
