# Generated by Django 5.0 on 2024-05-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0031_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.IntegerField(null=True),
        ),
    ]
