# Generated by Django 5.0 on 2024-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category_offer',
            fields=[
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discription', models.CharField(max_length=500, null=True)),
                ('eligible_price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
