# Generated by Django 5.0 on 2024-06-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0051_category_sold_out'),
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_offer',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category_offer', to='admin_product_app.category'),
        ),
        migrations.CreateModel(
            name='brand_offer',
            fields=[
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discription', models.CharField(max_length=500, null=True)),
                ('eligible_price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_offer', to='admin_product_app.brands')),
            ],
        ),
        migrations.CreateModel(
            name='product_offer',
            fields=[
                ('offer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discription', models.CharField(max_length=500, null=True)),
                ('eligible_price', models.IntegerField(default=0)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='admin_product_app.products')),
            ],
        ),
    ]
