# Generated by Django 5.0 on 2024-06-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0051_category_sold_out'),
        ('offer_app', '0002_category_offer_category_brand_offer_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offer', to='admin_product_app.category'),
        ),
    ]
