# Generated by Django 5.0 on 2024-06-06 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_category_offer_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_offer',
            old_name='category',
            new_name='offer_category',
        ),
    ]
