# Generated by Django 5.0 on 2023-12-29 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('category_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='productes',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_disc', models.CharField(max_length=500)),
                ('pro_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='admin_product_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='variants',
            fields=[
                ('variant_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_color', models.CharField(max_length=100)),
                ('variant_img', models.ImageField(upload_to='products/')),
                ('variant_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='admin_product_app.productes')),
            ],
        ),
    ]
