# Generated by Django 5.0 on 2023-12-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_disc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
