# Generated by Django 5.0 on 2023-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0003_productes_product_price_alter_productes_pro_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_image', models.ImageField(null=True, upload_to='brands/')),
            ],
        ),
    ]
