# Generated by Django 5.0 on 2023-12-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0005_brands_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_active',
            field=models.BooleanField(default=True),
        ),
    ]
