# Generated by Django 5.0 on 2023-12-30 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0006_brands_brand_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productes',
            name='pro_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pro_brand', to='admin_product_app.brands'),
            preserve_default=False,
        ),
    ]
