# Generated by Django 5.0 on 2023-12-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0007_productes_pro_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productes',
            new_name='products',
        ),
    ]
