# Generated by Django 5.0 on 2023-12-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0008_rename_productes_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
        migrations.AddField(
            model_name='variants',
            name='variant_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
