# Generated by Django 5.0 on 2024-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0009_remove_products_product_price_variants_variant_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_active',
            field=models.BooleanField(default=True),
        ),
    ]
