# Generated by Django 5.0 on 2024-01-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0010_products_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_image',
            field=models.ImageField(default='brands/brand_default_logo.png', upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_img',
            field=models.ImageField(default='products/user_default_image.png', upload_to='products/'),
        ),
    ]
