# Generated by Django 5.0 on 2024-01-06 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0011_alter_brands_brand_image_alter_variants_variant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='admin_product_app.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_brand', to='admin_product_app.brands'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='admin_product_app.category'),
        ),
    ]
