# Generated by Django 5.0 on 2024-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0013_alter_products_pro_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='varient_active',
            field=models.BooleanField(default=True),
        ),
    ]
