# Generated by Django 5.0 on 2024-01-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0014_variants_varient_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='varient_disc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
