# Generated by Django 5.0 on 2024-01-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0016_variants_varient_brand_variants_varient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image',
            field=models.ImageField(default='products/default_product.png', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_img',
            field=models.ImageField(default='variants/default_product.png', upload_to='variants/'),
        ),
    ]
