# Generated by Django 5.0 on 2024-01-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0017_products_product_image_alter_variants_variant_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='varient_active',
            new_name='variant_active',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='varient_brand',
            new_name='variant_brand',
        ),
        migrations.RenameField(
            model_name='variants',
            old_name='varient_disc',
            new_name='variant_disc',
        ),
    ]
