# Generated by Django 5.0 on 2024-01-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0019_rename_varient_category_variants_variant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='product_image',
        ),
        migrations.DeleteModel(
            name='variants',
        ),
    ]
