# Generated by Django 5.0 on 2024-01-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0020_remove_products_product_image_delete_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('color_name', models.CharField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='admin_product_app.products')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admin_product_app.colors')),
            ],
        ),
    ]
