# Generated by Django 5.0 on 2024-01-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0021_colors_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('ram', models.CharField()),
                ('rom', models.CharField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='admin_product_app.products')),
            ],
        ),
    ]
