# Generated by Django 5.0 on 2024-01-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0023_size_price_of_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['ram', 'rom']},
        ),
        migrations.AlterField(
            model_name='size',
            name='ram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='rom',
            field=models.IntegerField(),
        ),
    ]
