# Generated by Django 5.0 on 2024-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0026_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='ram',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='size',
            name='rom',
            field=models.CharField(),
        ),
    ]
