# Generated by Django 5.0 on 2024-01-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0028_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('size_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('ram', models.CharField()),
                ('rom', models.CharField()),
                ('price_of_size', models.CharField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='admin_product_app.colors')),
            ],
            options={
                'ordering': ['ram', 'rom'],
            },
        ),
    ]
