# Generated by Django 5.0 on 2024-01-24 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0030_remove_storage_color_storage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='admin_product_app.products'),
        ),
    ]
