# Generated by Django 5.0 on 2024-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0031_alter_storage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='product_thumbnail'),
            preserve_default=False,
        ),
    ]
