# Generated by Django 5.0 on 2024-01-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0032_products_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default='product_thumbnail/default_product_thumbnail.webp', upload_to='product_thumbnail'),
        ),
    ]
