# Generated by Django 5.0 on 2024-02-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0033_alter_products_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category/default.jpg', upload_to='category/'),
        ),
    ]
