# Generated by Django 5.0 on 2024-03-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0034_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='color_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_stock',
            field=models.IntegerField(default=0),
        ),
    ]
