# Generated by Django 5.0 on 2024-03-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0035_colors_color_stock_storage_storage_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_disc',
            field=models.CharField(max_length=1500),
        ),
    ]
