# Generated by Django 5.0 on 2024-03-07 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0036_alter_products_product_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='color_stock',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='storage_stock',
        ),
        migrations.AddField(
            model_name='storage',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='admin_product_app.colors'),
            preserve_default=False,
        ),
    ]
