# Generated by Django 5.0 on 2024-03-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0037_remove_colors_color_stock_remove_storage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
