# Generated by Django 5.0 on 2024-03-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0038_storage_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='admin_product_app.category'),
        ),
    ]
