# Generated by Django 5.0 on 2024-03-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0039_alter_brands_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbnail',
            field=models.ImageField(default='product_thumbnail/default_product_thumbnail.webp', upload_to='product_thumbnail/'),
        ),
    ]
