# Generated by Django 5.0 on 2024-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0040_alter_products_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
