# Generated by Django 5.0 on 2024-05-07 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0042_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color', to='admin_product_app.colors'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='storage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='admin_product_app.storage'),
        ),
    ]
