# Generated by Django 5.0 on 2024-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0043_wishlist_color_wishlist_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold_out',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
