# Generated by Django 5.0 on 2024-05-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0044_products_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='sold_out',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
