# Generated by Django 5.0 on 2024-05-14 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0045_brands_sold_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('saled_product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='admin_product_app.products')),
            ],
        ),
    ]
