# Generated by Django 5.0 on 2024-05-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0049_alter_brands_created_at_alter_brands_update_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
