# Generated by Django 5.0 on 2024-05-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_product_app', '0050_delete_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sold_out',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
