# Generated by Django 5.0 on 2023-12-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
