# Generated by Django 5.0 on 2023-12-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_userdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users_profile/'),
        ),
    ]
