# Generated by Django 5.0 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_userdetails_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='users_profile'),
        ),
    ]
