# Generated by Django 5.0 on 2023-12-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
