# Generated by Django 5.0 on 2023-12-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_userdetails_otp_alter_userdetails_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
