# Generated by Django 5.0 on 2023-12-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_userdetails_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdetails',
            managers=[
            ],
        ),
    ]
