# Generated by Django 5.0 on 2024-03-23 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_web_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_logo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 16, 54, 43, 180111)),
        ),
    ]
