# Generated by Django 5.0 on 2024-03-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_web_logo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_logo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
