# Generated by Django 5.0 on 2024-05-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_active',
        ),
    ]
