# Generated by Django 5.0 on 2024-05-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_address_address_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
