# Generated by Django 5.0 on 2024-05-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_address'),
        ('cart_app', '0013_remove_order_order_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
