# Generated by Django 5.0 on 2024-05-05 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_alter_wallet_user'),
        ('cart_app', '0024_order_is_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_history',
            fields=[
                ('history_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('credit', models.IntegerField(default=0, null=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_wallet', to='cart_app.order')),
                ('wallet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_history', to='admin_app.wallet')),
            ],
        ),
    ]
