# Generated by Django 5.0 on 2024-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_wallet_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
