# Generated by Django 5.0 on 2024-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_wallet_history_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
