# Generated by Django 5.0 on 2024-05-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_alter_wallet_history_created_at'),
        ('cart_app', '0024_order_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet_history',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_wallet', to='cart_app.order'),
        ),
    ]
