# Generated by Django 5.0 on 2024-05-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0022_alter_wallet_history_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_history',
            old_name='credit',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='wallet_history',
            name='status',
            field=models.CharField(default='Credit', null=True),
        ),
    ]
